name: Mirror and push

on: 
  workflow_dispatch:
  schedule:
    - cron:  '45 11 * * 3'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
     
    - name: Install requests
      run: pip install requests
 
    - name: Download
      run: |
        python dl.py
      
    - name: Releases mirror
      uses: ncipollo/release-action@v1
      with:
        artifacts: "output/scratch-win.exe,output/scratch-mac.dmg"
        token: ${{ secrets.PUBLISH }}
        body: " THIS IS AN MIRROR, FOR OFFICAL RELEASES, PLEASE GO HTTPS://SCRATCH.MIT.EDU/DOWNLOAD . "
        tag: ${{ github.run_id }}

    - name: Commit version info
      uses: EndBug/add-and-commit@v4
      with:
        message: "AUTO COMMIT SCRATCH VERSION INFO"
        add: "scratch-version"
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISH }}
